In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("archive/hantavirus_detection_dataset.csv")
df

,Patient_ID,Age,Gender,Region,Hantavirus_Positive,Hantavirus_Type,Symptoms,Symptom_Count,Exposure_Type,Sample_Date,...,ALT_U/L,AST_U/L,BUN_mg/dL,Creatinine_mg/dL,Disease_Severity,WBC_Platelet_Ratio,Creatinine_BUN_Ratio,Liver_Injury_Score,Immunological_Risk,Renal_Risk
0,PATIENT_00001,69,M,Asia,0,NaN,NaN,0,Rodent Contact,2025-01-23,...,22.1,24.7,10.6,0.38,NaN,0.026,0.036,23.4,Low,Low
1,PATIENT_00002,76,M,Europe,0,NaN,"Fever, Fatigue",2,Unknown,2025-02-12,...,12.7,41.8,13.2,0.84,NaN,0.037,0.064,27.2,Low,Low
2,PATIENT_00003,61,M,South America,0,NaN,Asymptomatic,1,Rodent Contact,2024-06-10,...,14.3,38.1,20.6,1.05,NaN,0.039,0.051,26.2,Low,Low
3,PATIENT_00004,57,M,South America,0,NaN,"Dyspnea, Headache",2,Unknown,2025-12-25,...,29.3,30.0,5.5,0.74,NaN,0.020,0.135,29.7,Low,Low
4,PATIENT_00005,25,M,Asia,1,Seoul,Abdominal Pain,1,Unknown,2024-09-07,...,45.7,133.0,60.9,2.56,Severe,0.030,0.042,89.3,Low,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,PATIENT_09996,61,M,North America,0,NaN,NaN,0,Unknown,2024-11-06,...,31.6,5.0,5.0,0.36,NaN,0.022,0.072,18.3,Low,Low
9996,PATIENT_09997,39,F,North America,0,NaN,NaN,0,Unknown,2024-08-27,...,47.5,34.1,15.7,1.02,NaN,0.025,0.065,40.8,Low,Low
9997,PATIENT_09998,45,M,Europe,0,NaN,"Cough, Dyspnea",2,Rodent Contact,2024-07-06,...,46.4,50.4,14.6,1.17,NaN,0.026,0.080,48.4,Low,Low
9998,PATIENT_09999,34,M,Asia,0,NaN,Cough,1,Rodent Contact,2025-10-28,...,39.4,27.6,24.9,0.57,NaN,0.034,0.023,33.5,Low,Low
9999,PATIENT_10000,52,M,South America,0,NaN,NaN,0,Rodent Contact,2025-12-21,...,68.5,59.4,8.2,0.94,NaN,0.027,0.115,63.9,Low,Low

In [24]:
df = df.drop(columns=['Patient_ID'])
df = df.drop(columns=['Immunological_Risk'])
df = df.drop(columns=['Disease_Onset_Date'])
df = df.drop(columns=['Sample_Date'])
df = df.drop(columns=['Gender'])
df = df.drop(columns=['Age'])
df = df.drop(columns=['Hantavirus_Type'])
df

,Region,Hantavirus_Positive,Symptoms,Symptom_Count,Exposure_Type,WBC_Count_K/uL,Platelet_Count_K/uL,CRP_mg/L,ALT_U/L,AST_U/L,BUN_mg/dL,Creatinine_mg/dL,Disease_Severity,WBC_Platelet_Ratio,Creatinine_BUN_Ratio,Liver_Injury_Score,Renal_Risk
0,Asia,0,NaN,0,Rodent Contact,7.42,290.42,3.26,22.1,24.7,10.6,0.38,NaN,0.026,0.036,23.4,Low
1,Europe,0,"Fever, Fatigue",2,Unknown,8.43,228.22,5.33,12.7,41.8,13.2,0.84,NaN,0.037,0.064,27.2,Low
2,South America,0,Asymptomatic,1,Rodent Contact,7.48,194.26,0.10,14.3,38.1,20.6,1.05,NaN,0.039,0.051,26.2,Low
3,South America,0,"Dyspnea, Headache",2,Unknown,4.25,216.26,3.46,29.3,30.0,5.5,0.74,NaN,0.020,0.135,29.7,Low
4,Asia,1,Abdominal Pain,1,Unknown,5.26,174.40,74.38,45.7,133.0,60.9,2.56,Severe,0.030,0.042,89.3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,North America,0,NaN,0,Unknown,5.37,242.37,9.22,31.6,5.0,5.0,0.36,NaN,0.022,0.072,18.3,Low
9996,North America,0,NaN,0,Unknown,6.36,251.11,3.43,47.5,34.1,15.7,1.02,NaN,0.025,0.065,40.8,Low
9997,Europe,0,"Cough, Dyspnea",2,Rodent Contact,7.27,276.09,2.88,46.4,50.4,14.6,1.17,NaN,0.026,0.080,48.4,Low
9998,Asia,0,Cough,1,Rodent Contact,8.08,240.01,9.80,39.4,27.6,24.9,0.57,NaN,0.034,0.023,33.5,Low
9999,South America,0,NaN,0,Rodent Contact,7.23,267.12,5.66,68.5,59.4,8.2,0.94,NaN,0.027,0.115,63.9,Low

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Region                0 non-null      float64
 1   Hantavirus_Positive   10000 non-null  int64
 2   Symptoms              1124 non-null   float64
 3   Symptom_Count         10000 non-null  int64
 4   Exposure_Type         3373 non-null   float64
 5   WBC_Count_K/uL        10000 non-null  float64
 6   Platelet_Count_K/uL   10000 non-null  float64
 7   CRP_mg/L              10000 non-null  float64
 8   ALT_U/L               10000 non-null  float64
 9   AST_U/L               10000 non-null  float64
 10  BUN_mg/dL             10000 non-null  float64
 11  Creatinine_mg/dL      10000 non-null  float64
 12  Disease_Severity      2571 non-null   float64
 13  WBC_Platelet_Ratio    10000 non-null  float64
 14  Creatinine_BUN_Ratio  10000 non-null  float64
 15  Liver_Injury_Score    10000 non-null  float64
 16  Renal_Risk            10000 non-null  int64
dtypes: float64(14), int64(3)
memory usage: 1.3 MB

In [42]:
df.memory_usage(deep=True)

Index                     132
Region                  80000
Hantavirus_Positive     80000
Symptoms                80000
Symptom_Count           80000
Exposure_Type           80000
WBC_Count_K/uL          80000
Platelet_Count_K/uL     80000
CRP_mg/L                80000
ALT_U/L                 80000
AST_U/L                 80000
BUN_mg/dL               80000
Creatinine_mg/dL        80000
Disease_Severity        80000
WBC_Platelet_Ratio      80000
Creatinine_BUN_Ratio    80000
Liver_Injury_Score      80000
Renal_Risk              80000
dtype: int64

In [50]:
df['Symptoms'].unique()

array([nan,  2.,  1.,  8.])

In [29]:
df['Symptoms'] = df['Symptoms'].map({'Fever': 1, 'Headache': 2, 'Muscle_Pain': 3, 'Nausea': 4, 'Vomiting': 5, 'Diarrhea': 6, 'Abdominal_Pain': 7, 'Cough': 8, 'Shortness_of_Breath': 9, 'Chills': 10, 'Dizziness': 11, 'Rash': 12, 'Bleeding': 13})

In [31]:
df['Renal_Risk'] = df['Renal_Risk'].map({'Low': 1, 'Medium': 2, 'High': 3})

In [35]:
df['Disease_Severity'] = df['Disease_Severity'].map({'Mild': 1, 'Moderate': 2, 'Severe': 3})

In [38]:
df['Region'] = df['Region'].map({'North': 1, 'South': 2, 'East': 3, 'West': 4, 'Central': 5})

In [41]:
df['Exposure_Type'] = df['Exposure_Type'].map({'Occupational': 1, 'Recreational': 2, 'Residential': 3, 'Unknown': 4})

In [52]:
df.describe()

,Region,Hantavirus_Positive,Symptoms,Symptom_Count,Exposure_Type,WBC_Count_K/uL,Platelet_Count_K/uL,CRP_mg/L,ALT_U/L,AST_U/L,BUN_mg/dL,Creatinine_mg/dL,Disease_Severity,WBC_Platelet_Ratio,Creatinine_BUN_Ratio,Liver_Injury_Score,Renal_Risk
count,0.0,10000.000000,1124.000000,10000.000000,3373.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,2571.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,NaN,0.257100,3.737544,1.399600,3.597984,7.172074,232.640248,15.499056,44.603360,50.282000,22.359360,1.205640,2.517697,0.033298,0.068618,47.442730,1.366400
std,NaN,0.437057,3.098498,1.296413,1.022126,1.805691,52.370778,20.464505,32.415649,35.837208,12.302045,0.739308,0.499784,0.016381,0.059178,30.065534,0.773699
min,NaN,0.000000,1.000000,0.000000,1.000000,2.000000,20.000000,0.100000,5.000000,5.000000,5.000000,0.300000,2.000000,0.006000,0.004000,5.000000,1.000000
25%,NaN,0.000000,1.000000,0.000000,4.000000,6.000000,201.287500,3.740000,23.200000,26.200000,14.000000,0.800000,2.000000,0.024000,0.037000,27.600000,1.000000
50%,NaN,0.000000,2.000000,1.000000,4.000000,7.130000,237.625000,6.345000,35.800000,41.000000,20.200000,0.970000,3.000000,0.030000,0.052000,37.400000,1.000000
75%,NaN,1.000000,8.000000,2.000000,4.000000,8.280000,268.692500,12.335000,54.700000,62.000000,28.000000,1.220000,3.000000,0.038000,0.079000,55.300000,1.000000
max,NaN,1.000000,8.000000,5.000000,4.000000,15.370000,403.400000,115.120000,190.100000,226.400000,90.300000,5.910000,3.000000,0.488000,0.888000,197.700000,3.000000

In [53]:
df.to_csv("archive/hantavirus_detection_dataset_preprocessed.csv", index=False)